language: php
php: 7.1
before_script:
    - composer install
script:
  - ./vendor/bin/phpcs .
  - ./vendor/bin/phpunit -v --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
    - travis_retry php coveralls.phar -v
notifications:
  email: false
  irc: "chat.freenode.net#thechurch"
