language: php
php: 7.1
before_script:
    - composer install
script: ./vendor/bin/phpunit -v --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  email: false
  irc: "chat.freenode.net#thechurch"
