language: php
php: 7.1
before_script:
    - composer install
script: phpunit -v --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  irc: "chat.freenode.net#thechurch"
