<?php

/**
 * @file
 * A module that creates the ability to add a 'post'.
 */


/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function thechurch_posts_form_post_node_form_alter(&$form, &$form_state, $form_id) {
	
	// Define the Variables
	$tid = null;
	
	// Get the Current path, if it's a taxonomy, set that to as the taxonomy id
	if (arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2))) {
			$tid = arg(2);
	}

	// if the taxonomy is null, set it to the user's city.
	if ($tid == null) {
		global $user;
		$user = user_load($user->uid);
		if (isset($user->field_city['und'][0]['tid'])) {
			$tid = $user->field_city['und'][0]['tid'];
		}
	}
	
	// Set the Field City to the Current Term id.
	$form['field_city']['und']['#default_value'][0] = $tid;
	
	// Make sure the form can only be accessed by people who have the right to create posts
	$form['#access'] = user_access('create post content');
	
	// No one should have access to the city field
	$form['field_city']['#access'] = false;
	
	// The title should be unset since it will be set later.
	unset($form['body']['und'][0]['#title']);
	
	// The form's body field should not include the default 'resizable' javascript.
	$form['body']['und'][0]['#resizable'] = FALSE;
	
	// Make the Body a Required Field
	$form['body']['und'][0]['#required'] = TRUE;
	
	// Rename the 'Submit' button to 'Share'
	$form['actions']['submit']['#value'] = 'Share';
	
	$form['actions']['submit']['#ajax'] = array(
		'callback' => 'thechurch_posts_ajax_callback',
		'progress' => false,
	);
	
	// No one should have access to the additional options
	$form['additional_settings']['#access'] = false;
	
	form_load_include($form_state, 'inc', 'node', 'node.pages');
	
}

/**
 * Implementation of hook_filter_info().
 */
function thechurch_posts_filter_info() {
	
	// Set up the Trim Link Filter
	$filters['filter_trimlink'] = array(
    'title' => t('Trim Well-Formed Links'), 
    'description' => t("Trims the 'http' and 'www' from well-formed links."), 
    'process callback' => 'thechurch_posts_filter_trimlink_process', 
  );
  return $filters;
}

/**
 * Implementation of hook_filter_FILTER_process().
 */
function thechurch_posts_filter_trimlink_process($text, $filter, $format, $langcode, $cache, $cache_id) {
	
	// Process the Trim Link Filter
	$text = preg_replace("/(>http:\/\/www\\.|>https:\/\/www\\.)|(>http:\/\/|>https:\/\/)/us", ">", $text);
	$text = preg_replace("/\/</us", "<", $text);
  return $text;
  
}

/**
 * Add Comments to Node
 */
function thechurch_posts_attach_comments($node) {
	$node->content['comments'] = comment_node_page_additions($node);
	unset($node->content['comments']['comments']['pager']);
	$comments_per_page = variable_get('comment_default_per_page_' . $node->type, 50);
	if ($node->comment_count > $comments_per_page) {
		$items = array(
			l(t('next ›'), 'node/'.$node->nid, array('attributes' => array('class' => 'pager-next'), 'query' => array('page' => 1))),
		);
		$node->content['comments']['comments']['pager'] = array(
			'#theme' => 'item_list',
   		'#items' => $items,
    	'#attributes' => array('class' => array('pager-next')),
  	);
	}
}


/**
 * Implementation of hook_node_view().
 */
function thechurch_posts_node_view($node, $view_mode, $langcode) {
	if ((arg(0) == 'taxonomy' && arg(1) == 'term' && is_numeric(arg(2)) && arg(3) != 'feed') ||(arg(0) == 'system' && arg(1) == 'ajax')) {
		thechurch_posts_attach_comments(&$node);
	}
}

/**
 * Implementation of hook_menu_alter().
 */
function thechurch_posts_menu_alter(&$items) {

	// Set up the Ajax Delivery of Delete Comments Link
  $items['node/%node/delete/ajax'] = $items['node/%node/delete'];
  $items['node/%node/delete/ajax']['delivery callback'] = 'ajax_deliver';
  $items['node/%node/delete/ajax']['page callback'] = 'thechurch_posts_ajax_confirm_delete_page';
  $items['node/%node/delete/ajax']['type'] = MENU_CALLBACK;
  
}

/**
 * Node Delete Link Ajax Callback.
 */
function thechurch_posts_ajax_confirm_delete_page($form, $node) {

	if ($node->nid) {

    $form = drupal_get_form($form, $node);
		
    $data = drupal_render($form);
  }
  
  // Put all of the Ajax Commands into an array
	$commands = array();
	
	// Fade out the Comment so the Delete Form can take Precidence
	$commands[] = ajax_command_invoke('#node-'.$node->nid, 'hide');
	
	// Append the Delete Form
	$commands[] = ajax_command_after('#node-'.$node->nid, $data, array('effect' => 'fade'));
	
	$commands[] = ajax_command_invoke(null, "reAttach", array());
	
	// Mark it as changed
	$commands[] = ajax_command_changed('#node-'.$nid);
	
	return array('#type' => 'ajax', '#commands' => $commands);
  
}


/**
 * Implementation of hook_form_BASE_FORM_ID_alter().
 */
function thechurch_posts_form_node_delete_confirm_alter(&$form, &$form_state, $form_id) {
	// Get the Comment
	$node = $form['#node'];
	
	$form['description']['#markup'] = t('Any replies to this @type will be lost. This action cannot be undone.', array('@type' => $node->type));
	// Add the Ajax Submit Function
	$form['actions']['submit']['#ajax'] = array(
		'callback' => 'thechurch_posts_ajax_delete',
		'progress' => false,
	);
	
	// Get the Comment
	$node = $form['#node'];
	
	// Give the Comment a Proper, Numerical ID
	$form['#id'] = 'node-'.$node->nid.'-confirm-delete';
	$form['#attributes']['class'][] = 'confirm-delete';
	
}

/**
 * Node Ajax Callback.
 */
function thechurch_posts_ajax_delete($form, $form_state) {
	
	// Get rid of all of the messages that have been set
	drupal_get_messages();

	// Get the comment & node objects
	$node = $form['#node'];
	
	// Put all of the Ajax Commands into an array
	$commands = array();
	
	// FadeOut the deleted comment
	$commands[] = ajax_command_invoke('#node-'.$node->nid.'-confirm-delete', 'fadeOut');
		
	// Return the Ajax Commands Array
  return array('#type' => 'ajax', '#commands' => $commands);
	
}

/**
 * Node Ajax Callback.
 */
function thechurch_posts_ajax_callback($form, $form_state) {
	
	// Get rid of all of the messages that have been set
	drupal_get_messages();

	// Get the comment & node objects
	$node = $form_state['node'];
	$node = node_load($node->nid);
	
	// Put all of the Ajax Commands into an array
	$commands = array();
	
	// Make sure that comment was actually loaded before proceeding. 
	if (!empty($node->nid) && $form_state['executed']) {
	
		// Generate the Array for Drupal Render
		$node_build = node_view($node, 'teaser');
			
		// Render the Array
		$html = drupal_render($node_build);
	
		// Place the comment above the form
		$commands[] = ajax_command_after(".term-listing-heading", '<div class="new-node" style="display: none;">'.$html.'</div>');
		
		$commands[] = ajax_command_invoke('.new-node', 'animate', array(
			array(
				'height' => 'toggle',
				'opacity' => 'toggle',
			),
			'slow',
		));
		
		$commands[] = ajax_command_invoke(".new-node", 'removeClass', array('new-node'));
		
		// Reset the textarea back to it's original color
		$commands[] = ajax_command_invoke(".node-form", 'removeClass', array('progress'));
				
		// Remove the text in the text field
		$commands[] = ajax_command_invoke(".node-form textarea", 'val', array(''));
	
		// Reset the text area back to it's original height
		$commands[] = ajax_command_css(".node-form textarea", array('height' => '50px'));
		
		
	}
	
	// Reset the textarea back to it's original color
	$commands[] = ajax_command_invoke(".node-form", 'removeClass', array('progress'));
	
	// Return the Ajax Commands Array
	return array('#type' => 'ajax', '#commands' => $commands);
	
}