user:
    resource: '@Church/Controller/UserController.php'
    type:     annotation

user_logout:
    path: /u/logout

me:
    resource: '@Church/Controller/MeController.php'
    type:     annotation

place:
    resource: '@Church/Controller/PlaceController.php'
    type:     annotation

csrf:
    resource: '@Church/Controller/CsrfController.php'
    type:     annotation

default:
    resource: '@Church/Controller/DefaultController.php'
    type:     annotation
