church_make_it_happen:
    resource: "@ChurchMakeItHappenBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  [https]

church_teaser:
    resource: "@ChurchTeaserBundle/Resources/config/routing.yml"
    prefix:   /
    schemes:  [https]

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
