# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:

services:

  church.tree_maker:
     class: Church\EventListener\TreeMaker
     tags:
         - { name: doctrine.event_listener, event: postPersist }
         - { name: doctrine.event_listener, event: preUpdate }
         - { name: doctrine.event_listener, event: preRemove }

  church.validator.login:
        class: Church\Validator\Constraints\LoginValidator
        arguments: [@egulias.email_validator, @giggsey.phone_validator]
        tags:
            - { name: validator.constraint_validator, alias: valid_login }

  church.user_create:
      class: Church\Utils\UserCreate
      arguments: [@doctrine]

  church.code_authenticator:
        class:     Church\Security\CodeAuthenticator
        arguments: [@doctrine, @security.http_utils]

  church.verify_create:
      class: Church\Utils\VerifyCreate
      arguments:
        - @doctrine
        - @ircmaxell.random
        - @church.validator.login
        - @church.user_create

  church.verify_send:
      class: Church\Utils\VerifySend
      arguments: [@church.dispatcher_email, @church.dispatcher_sms, @router]

  church.dispatcher_email:
      class: Church\Utils\Dispatcher\Email
      arguments: [@hip_mandrill.dispatcher]

  church.dispatcher_sms:
      class: Church\Utils\Dispatcher\SMS
      arguments: [@prawnsalad.nexmo, %nexmo_sender%]

  church.place_finder:
    class: Church\Utils\PlaceFinder
    arguments: [@doctrine, @church.client_yahoo_geoplanet]
    #church_place.consumer_key: ~
    #church_place.consumer_secret: ~
    #church_place.generic_appid: ~

  church.client_yahoo_geoplanet:
      class: Church\Client\Yahoo\GeoPlanet
      arguments: [@guzzlehttp.client_yahoo_geoplanet]

  church.client_yahoo_placefinder:
      class: Church\Client\Yahoo\PlaceFinder
      arguments:
        - @guzzlehttp.client_yahoo_boss_placefinder
        - @guzzlehttp.client_yahoo_yql_placefinder
        - @guzzlehttp.oauth_yahoo

  egulias.email_validator:
        class: Egulias\EmailValidator\EmailValidator

  giggsey.phone_validator:
        class: libphonenumber\PhoneNumberUtil
        factory: [libphonenumber\PhoneNumberUtil, getInstance]

  ircmaxell.random_factory:
        class: RandomLib\Factory

  ircmaxell.random:
        class: RandomLib\Generator
        factory: ["@ircmaxell.random_factory", getMediumStrengthGenerator]

  prawnsalad.nexmo:
        class: NexmoMessage
        arguments: [%nexmo_api_key%, %nexmo_api_secret%]

  guzzlehttp.client_yahoo_geoplanet:
       class: GuzzleHttp\Client
       arguments:
         -
           base_url: http://where.yahooapis.com/v1/
           defaults:
             query:
               format: json
               appid: %yahoo_consumer_key%

  guzzlehttp.oauth_yahoo:
      class: GuzzleHttp\Subscriber\Oauth\Oauth1
      arguments:
        -
          consumer_key: %yahoo_consumer_key%
          consumer_secret: %yahoo_consumer_secret%

  guzzlehttp.client_yahoo_geoplanet:
       class: GuzzleHttp\Client
       arguments:
         -
           base_url: http://where.yahooapis.com/v1/
           defaults:
             query:
               format: json
               appid: %yahoo_consumer_key%

  guzzlehttp.client_yahoo_boss_placefinder:
       class: GuzzleHttp\Client
       arguments:
         -
           base_url: https://yboss.yahooapis.com/geo/placefinder
           defaults:
             auth: oauth

  guzzlehttp.client_yahoo_yql_placefinder:
       class: GuzzleHttp\Client
       arguments:
         -
           base_url: https://query.yahooapis.com/v1/public/yql
           defaults:
             auth: oauth
             query:
               format: json
