# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:

services:

  church.tree_maker:
     class: Church\EventListener\TreeMaker
     tags:
         - { name: doctrine.event_listener, event: postPersist }
         - { name: doctrine.event_listener, event: preUpdate }
         - { name: doctrine.event_listener, event: preRemove }

  church.place_finder:
    class: Church\Utils\PlaceFinder
    arguments: [@doctrine.orm.entity_manager, %place_finder%]
    church_place.consumer_key: ~
    church_place.consumer_secret: ~
    church_place.generic_appid: ~

  church.validator.login:
        class: Church\Validator\Constraints\LoginValidator
        arguments: [@egulias.email_validator, @giggsey.phone_validator]
        tags:
            - { name: validator.constraint_validator, alias: valid_login }

  church.user_create:
      class: Church\Utils\UserCreate
      arguments: [@doctrine]

  church.verify_create:
      class: Church\Utils\VerifyCreate
      arguments: [@doctrine, @ircmaxell.random, @church.validator.login, @church.user_create]

  church.verify_send:
      class: Church\Utils\VerifySend
      arguments: [@church.dispatcher_email, @church.dispatcher_sms, @router]

  church.dispatcher_email:
      class: Church\Utils\Dispatcher\Email
      arguments: [@hip_mandrill.dispatcher]

  church.dispatcher_sms:
      class: Church\Utils\Dispatcher\SMS
      arguments: [@prawnsalad.nexmo, %nexmo_sender%]

  egulias.email_validator:
        class: Egulias\EmailValidator\EmailValidator

  giggsey.phone_validator:
        class: libphonenumber\PhoneNumberUtil
        factory: [libphonenumber\PhoneNumberUtil, getInstance]

  ircmaxell.random_factory:
        class: RandomLib\Factory

  ircmaxell.random:
        class: RandomLib\Generator
        factory: ["@ircmaxell.random_factory", getMediumStrengthGenerator]

  prawnsalad.nexmo:
        class: NexmoMessage
        arguments: [%nexmo_api_key%, %nexmo_api_secret%]
