# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:

services:
    church.controller:
        abstract:  true
        arguments:
            - '@serializer'
            - '@validator'
            - '@doctrine'
            - '@security.token_storage'

    church.controller_default:
        parent: church.controller
        class: Church\Controller\DefaultController

    church.controller_csrf:
        parent: church.controller
        class: Church\Controller\CsrfController
        arguments:
            - '@security.csrf.token_manager'

    church.controller_me:
        parent: church.controller
        class: Church\Controller\MeController
        arguments:
            - "@church.verification_manager"
            - '@security.csrf.token_manager'
            - '@church.place_finder'

    church.controller_user:
        parent: church.controller
        class: Church\Controller\UserController

    church.controller_place:
        parent: church.controller
        class: Church\Controller\PlaceController

    church.normalizer_csrf_token:
        class: Church\Serializer\CsrfTokenNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    church.exception_listener:
        parent: church.controller
        class: Church\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    church.csrf_token_listener:
        class: Church\EventListener\CsrfToken
        arguments:
            - '@security.csrf.token_manager'
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    church.tree_maker:
        class: Church\EventListener\TreeMaker
        public: false
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: preRemove }

    church.code_authenticator:
        parent: church.controller
        class: Church\Security\CodeAuthenticator
        arguments:
            - '@security.http_utils'

    church.verification_manager:
         class: Church\Utils\User\VerificationManager

    church.verification_email:
        class: Church\Utils\User\EmailVerification
        public: false
        arguments:
            - '@doctrine'
            - '@ircmaxell.random'
            - '@church.dispatcher_email'
        tags:
            - { name: church.verification, type: email }

    church.dispatcher_email:
        class: Church\Utils\Dispatcher\EmailDispatcher
        arguments:
            - '%dispatch%'
            - '@sendgrid'

    church.place_finder:
        class: Church\Utils\PlaceFinder
        arguments:
            - '@doctrine'
            - '@church.client_mapzen_search'
            - '@church.client_mapzen_whos_on_first'
            - '@church.slug'

    church.slug:
        class: Church\Utils\Slug

    egulias.email_validator:
        class: Egulias\EmailValidator\EmailValidator

    sendgrid:
        class: SendGrid
        arguments:
            - '%sendgrid_api_key%'

    ircmaxell.random_factory:
        class: RandomLib\Factory

    ircmaxell.random:
        class: RandomLib\Generator
        factory: ["@ircmaxell.random_factory", getMediumStrengthGenerator]

    # prawnsalad.nexmo:
    #     class: NexmoMessage
    #     arguments:
    #         - '%nexmo_api_key%'
    #         - '%nexmo_api_secret%'

    church.client_mapzen_search:
        class: Church\Client\Mapzen\Search
        arguments:
            - '@guzzlehttp.client_mapzen_search'
            - '@serializer'

    church.client_mapzen_whos_on_first:
        class: Church\Client\Mapzen\WhosOnFirst
        arguments:
            - '@guzzlehttp.client_mapzen_whos_on_first'
            - '@serializer'

    church.serializer_mapzen_search:
        class: Church\Serializer\Mapzen\SearchDenormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    church.serializer_mapzen_whos_on_first:
        class: Church\Serializer\Mapzen\WhosOnFirstDenormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    guzzlehttp.client_mapzen_search:
        class: GuzzleHttp\Client
        arguments:
            -
                base_url: https://search.mapzen.com/v1/
                defaults:
                    query:
                        api_key: '%mapzen_api_key%'

    guzzlehttp.client_mapzen_whos_on_first:
        class: GuzzleHttp\Client
        arguments:
            -
                base_url: https://whosonfirst-api.mapzen.com
                defaults:
                    query:
                        api_key: '%mapzen_api_key%'
