parameters:
#    church_place.example.class: Church\PlaceBundle\Example

services:
#    church_place.example:
#        class: %church_place.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
