parameters:
#    david_barratt_make_it_happen.example.class: DavidBarratt\MakeItHappenBundle\Example

services:
#    david_barratt_make_it_happen.example:
#        class: %david_barratt_make_it_happen.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
