church_user_login_register:
  pattern: /login-register
  defaults: {_controller: ChurchUserBundle:Default:loginRegister}

church_user_register:
    pattern:  /register
    defaults: { _controller: ChurchUserBundle:Default:register }
    requirements:
        _method:  POST

church_user_register_email:
    pattern:  /register/email
    defaults: { _controller: ChurchUserBundle:Registration:email }
    requirements:
        _method:  POST

church_user_verify_email:
    pattern: /{user_id}/verify/email/{token}
    defaults: { _controller: ChurchUserBundle:Verification:email }
    requirements:
      user_id: \d+

church_user_login_check:
    pattern: /login_check
    requirements:
        _method:  POST

church_user_logout:
    pattern: /logout
