<?php
// $Id$

/**
 * @file
 * A module that customizes a user's profile
 *
 * This module usese several hooks to make a user's profile and edit screen fullfill its desired needs.
 */

/**
 * Implements hook_form_alter().
 */
function customprofile_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_profile_form') {
    $form['field_woeid']['#access'] = user_access('administer users');
    $form['field_city']['#access'] = user_access('administer users');
    $form['field_latitude']['#access'] = user_access('administer users');
    $form['field_longitude']['#access'] = user_access('administer users');
  }

}
