church_user_register:
    pattern:  /register
    defaults: { _controller: ChurchUserBundle:Default:register }
    
church_user_login:
    pattern: /login
    defaults: { _controller: ChurchUserBundle:Security:login }
    
church_user_login_check:
    pattern: /login_check
    
church_user_logout:
    pattern: /logout
