parameters:
#    church_user.example.class: Church\UserBundle\Example

services:
#    church_user.example:
#        class: %church_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
